
services:


  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    platform: linux/amd64
    depends_on:
      - postgres
    # environment:
    #   - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ZooDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=true;
    ports:
      - "80:80"
    networks:
      - digital-wallet

volumes:
  postgres_data:


networks:
  digital-wallet:
    driver: bridge



